In [1]:
# 1. Create a null vector of size 10 but the fifth value which is 1.


In [2]:
import numpy as np
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
null_vector[4]= 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [8]:
# 2. Create a vector with values ranging from 10 to 49.

In [10]:
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [11]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
matrix = np.arange(9)
matrix

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
matrix = np.arange(9).reshape((3,3))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [20]:
array1 = np.array([1,2,0,0,4,0])
non_zero = np.nonzero(array1)
print(non_zero)

(array([0, 1, 4], dtype=int64),)


In [21]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [24]:
array2 = np.random.random((10,10))
array2


array([[0.81744333, 0.12931924, 0.29148937, 0.06599687, 0.56389913,
        0.1932963 , 0.74355031, 0.85739683, 0.95784475, 0.12621082],
       [0.16904148, 0.33872613, 0.11328399, 0.31372364, 0.27727235,
        0.67724285, 0.67308631, 0.48288554, 0.50410776, 0.34103911],
       [0.23017314, 0.56124295, 0.11517962, 0.11960102, 0.84196467,
        0.7090585 , 0.52818811, 0.73581059, 0.41919103, 0.59442885],
       [0.64298094, 0.73385185, 0.42695456, 0.30960592, 0.23976283,
        0.73376493, 0.10619028, 0.75856896, 0.13525816, 0.28750453],
       [0.90815391, 0.68707901, 0.13734994, 0.52047542, 0.31973467,
        0.72953459, 0.65392898, 0.91912334, 0.16466393, 0.66955554],
       [0.87701302, 0.18833299, 0.47830746, 0.7116936 , 0.67260158,
        0.81167538, 0.02175275, 0.08361609, 0.6889546 , 0.67239112],
       [0.41649563, 0.91201527, 0.31135313, 0.73054645, 0.26047557,
        0.16610721, 0.78804034, 0.35409173, 0.09803337, 0.80716317],
       [0.02013287, 0.14378543, 0.7682789

In [28]:
min_value = np.min(array2)
min_value


0.02013286803715264

In [29]:
max_value = np.max(array2)
max_value

0.993453736113448

In [30]:
# 6. Create a random vector of size 30 and find the mean value.

In [31]:
random_vector = np.random.random(30)
random_vector

array([0.59746065, 0.51111755, 0.52301127, 0.81945097, 0.85272476,
       0.90135576, 0.18876949, 0.84918016, 0.07775253, 0.78080403,
       0.90465542, 0.67112263, 0.47344202, 0.28191962, 0.61083926,
       0.34107695, 0.52361838, 0.17308721, 0.9911136 , 0.84799475,
       0.56487152, 0.53840047, 0.60340427, 0.64011613, 0.1282813 ,
       0.57520163, 0.68965647, 0.97873365, 0.35680035, 0.0632247 ])

In [32]:
mean_value = np.mean(random_vector)
mean_value

0.5686395822876091